### ISSUE TITLE
Package issue 

### ISSUE THREAD

**Issue by drinkwater99** [telerik/ui-for-blazor-examples#11] opened 2019-04-01 00:46 UTC
Receiving the following error 

NU1605	Detected package downgrade: Microsoft.NETCore.Platforms from 3.0.0-preview4.19120.16 to 3.0.0-preview3.19128.7. Reference the package directly from the project to select a different version. 
 
TelerikBlazor.Server -> TelerikBlazor.Client -> Telerik.UI.for.Blazor 0.3.0 -> Microsoft.Extensions.DependencyInjection 3.0.0-preview4.19121.1 -> Microsoft.NETCore.Platforms (>= 3.0.0-preview4.19120.16) 
 TelerikBlazor.Server -> Microsoft.NETCore.Platforms (>= 3.0.0-preview3.19128.7)	TelerikBlazor.Server	C:\Users\angel\Downloads\ui-for-blazor-examples-master\TelerikBlazor.Server\TelerikBlazor.Server.csproj	1

**Comment by drinkwater99** [comment] 2019-04-03 23:20
Wow incredible follow-up...guess will go with DevExpress they just released a Blazor preview.

**Comment by ivanchev** [comment] 2019-04-04 07:16
We're looking at the issue now. From our testing it's only observed in Visual Studio 2019, and wasn't around in the Preview version, which is why we haven't noticed it earlier.

**Comment by joelhays** [comment] 2019-04-05 00:01
Same issue here. Using Visual Studio Professional 2019 version 16.0.0 and dotnet version 3.0.100-preview3-010431

**Comment by ivanchev** [comment] 2019-04-05 14:19
The issue is caused by a package, that was previously available, but that's no longer the case. Our testing falled back to nuget cache, which is why we weren't able to see it. The issue will be fixed in Tuesday's 0.4 release, together with all the new features we're currently working on

**Comment by ivanchev** [comment] 2019-04-09 19:39
The 0.4.0 version is out and the issue is resolved.

**Closed by ivanchev** 2019-04-09 19:39 UTC

**Comment by joelhays** [comment] 2019-04-09 22:34
@ivanchev that works now. FYI, you may want to update this related blog post as it's now inaccurate. https://www.telerik.com/blogs/introducing-the-telerik-ui-for-blazor-early-preview.

I had to change _ViewImports from `@addTagHelper *,Kendo.Blazor` to `@addTagHelper *,Telerik.Blazor` and `services.AddKendoBlazor();` to `services.AddTelerikBlazor();`
